# Generated by Django 4.0.3 on 2022-03-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table='serviceprovider',
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='usermaster',
        ),
    ]
